package:
  name: kaldifeat
  version: "1.20"

source:
  path: "{{ environ.get('KALDIFEAT_ROOT_DIR') }}"

build:
  number: 0
  string: cuda{{ environ.get('KALDIFEAT_CUDA_VERSION') }}_py{{ environ.get('KALDIFEAT_PYTHON_VERSION') }}_torch{{ environ.get('KALDIFEAT_TORCH_VERSION') }}
  script_env:
    - KALDIFEAT_IS_GITHUB_ACTIONS
    - KALDIFEAT_CUDA_VERSION
    - KALDIFEAT_TORCH_VERSION
    - KALDIFEAT_PYTHON_VERSION
    - KALDIFEAT_BUILD_TYPE
    - KALDIFEAT_BUILD_VERSION
    - KALDIFEAT_IS_FOR_CONDA

requirements:
  host:
    - cmake=3.18
    - python
    - pytorch={{ environ.get('KALDIFEAT_TORCH_VERSION') }}
    - cudatoolkit={{ environ.get('KALDIFEAT_CUDA_VERSION') }}
    - gcc_linux-64=7
  run:
    - python
    - pytorch={{ environ.get('KALDIFEAT_TORCH_VERSION') }}
    - cudatoolkit={{ environ.get('KALDIFEAT_CUDA_VERSION') }}

about:
  home: https://github.com/csukuangfj/kaldifeat
  license: Apache V2
  license_file: LICENSE
  summary: Kaldi-compatible feature extraction with PyTorch
  description: |
    Kaldi-compatible feature extraction with PyTorch,
    supporting CUDA, batch processing, chunk processing, and autograd
