
.PHONY: test
test:
	python3 ./test_fbank.py
	python3 ./test_fbank_options.py
	python3 ./test_frame_extraction_options.py
	python3 ./test_mel_bank_options.py
	python3 ./test_mfcc.py
	python3 ./test_mfcc_options.py
	python3 ./test_plp.py
	python3 ./test_plp_options.py
	python3 ./test_spectrogram.py
	python3 ./test_spectrogram_options.py
