package:
  name: kaldifeat
  version: "1.20"

source:
  path: "{{ environ.get('KALDIFEAT_ROOT_DIR') }}"

build:
  number: 0
  string: cpu_py{{ environ.get('KALDIFEAT_PYTHON_VERSION') }}_torch{{ environ.get('KALDIFEAT_TORCH_VERSION') }}
  script: conda install -y -q -c pytorch pytorch={{ environ.get('KALDIFEAT_TORCH_VERSION') }} cpuonly & {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  features:
    - cpuonly # [not osx]

requirements:
  build:
    - {{ compiler('c') }} # [win]
    - {{ compiler('cxx') }} # [win]

  host:
    - anaconda-client
    - cmake
    - python
    - pytorch={{ environ.get('KALDIFEAT_TORCH_VERSION') }}
    - cpuonly

  run:
    - python
    - pytorch={{ environ.get('KALDIFEAT_TORCH_VERSION') }}

about:
  home: https://github.com/csukuangfj/kaldifeat
  license: Apache V2
  license_file: LICENSE
  summary: Kaldi-compatible feature extraction with PyTorch
  description: |
    Kaldi-compatible feature extraction with PyTorch,
    supporting CUDA, batch processing, chunk processing, and autograd
