# Copyright      2021  Xiaomi Corp.       (author: Fangjun Kuang)

# See ../../LICENSE for clarification regarding multiple authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Nightly tests ubuntu conda cpu

on:
  schedule:
    # minute (0-59)
    # hour (0-23)
    # day of the month (1-31)
    # month (1-12)
    # day of the week (0-6)
    # nightly build at 23:50 UTC time every day
    - cron: "50 23 * * *"

jobs:
  enable_nightly_build:
    runs-on: ubuntu-latest
    outputs:
      enabled: ${{ steps.set-enabled.outputs.enabled }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set enabled
        id: set-enabled
        run: |
          enabled=$(python scripts/github_actions/run-nightly-build.py)
          echo "enabled: $enabled"
          echo "::set-output name=enabled::${enabled}"

  generate_build_matrix:
    needs: enable_nightly_build
    if: needs.enable_nightly_build.outputs.enabled == 'true'
    # see https://github.com/pytorch/pytorch/pull/50633
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generating build matrix
        id: set-matrix
        run: |
          # outputting for debugging purposes
          python scripts/github_actions/generate_build_matrix.py --test-only-latest-torch
          MATRIX=$(python scripts/github_actions/generate_build_matrix.py --test-only-latest-torch)
          echo "::set-output name=matrix::${MATRIX}"

  run_nightly_tests_ubuntu_conda_cpu:
    needs: generate_build_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJson(needs.generate_build_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: kaldifeat

      - name: Display Python version
        shell: bash -l {0}
        run: |
          python3 -c "import sys; print(sys.version)"
          which python3

      - name: Install kaldifeat and run tests
        shell: bash -l {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1-dev libsndfile1 ffmpeg

          conda install -y -c kaldifeat -c pytorch cpuonly pytorch=${{ matrix.torch }} kaldifeat python=${{ matrix.python-version }}
          conda install -y -c conda-forge pysoundfile


          cd kaldifeat/python/tests
          make test
